#server.port=8001


#spring.datasource.url=jdbc:mysql://localhost:3306/product_db
#spring.datasource.username=root
#spring.datasource.password=getoffer
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

#yaml file port
server:
  port: 8001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/iproductdb
    username: root
    password: getoffer
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: product_service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}


